export const CHANGE_SEARCH_FIELD  = 'CHANGE_SEARCH_FIELD';

export const REQUEST_KITTIES_PENDING = 'REQUEST_KITTIES_PENDING';
export const REQUEST_KITTIES_SUCCESS = 'REQUEST_KITTIES_SUCCESS';
export const REQUEST_KITTIES_FAILED = 'REQUEST_KITTIES_FAILED';